[package]
name = "tjcl_error_format"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Static string formatting for tjcl_error in no_std embedded systems"

[dependencies]
tjcl_error_common = { path = "../common_error", version = "0.0.1" }
