[package]
name = "tjcl_error_common"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Zero-allocation packed error handling template for no_std embedded systems"
